import React, { useState, useEffect, useCallback } from 'react';
import { GameShell } from '../components/GameShell';
import { getGameById } from '../data/games';
import { playMoveSound, playClearSound, playGameOverSound, triggerHaptic } from '../utils/sound';
import { Clock, Lightbulb, Eraser, Edit3, RotateCcw, Sparkles } from 'lucide-react';

type Difficulty = 'easy' | 'medium' | 'hard';

// Base solved Sudoku template from which valid unique puzzles are generated by digit mapping and permutations
const BASE_SOLUTION = [
  [5, 3, 4, 6, 7, 8, 9, 1, 2],
  [6, 7, 2, 1, 9, 5, 3, 4, 8],
  [1, 9, 8, 3, 4, 2, 5, 6, 7],
  [8, 5, 9, 7, 6, 1, 4, 2, 3],
  [4, 2, 6, 8, 5, 3, 7, 9, 1],
  [7, 1, 3, 9, 2, 4, 8, 5, 6],
  [9, 6, 1, 5, 3, 7, 2, 8, 4],
  [2, 8, 7, 4, 1, 9, 6, 3, 5],
  [3, 4, 5, 2, 8, 6, 1, 7, 9],
];

interface SudokuGameProps {
  onBackToHub: () => void;
}

export const SudokuGame: React.FC<SudokuGameProps> = ({ onBackToHub }) => {
  const gameMeta = getGameById('sudoku')!;

  const [difficulty, setDifficulty] = useState<Difficulty>('easy');
  const [initialBoard, setInitialBoard] = useState<number[][]>([]);
  const [board, setBoard] = useState<number[][]>([]);
  const [solution, setSolution] = useState<number[][]>([]);
  const [notes, setNotes] = useState<Record<string, number[]>>({});
  const [selectedCell, setSelectedCell] = useState<[number, number] | null>([0, 0]);
  const [notesMode, setNotesMode] = useState(false);
  const [hintsLeft, setHintsLeft] = useState(3);
  const [timer, setTimer] = useState(0);
  const [isTimerRunning, setIsTimerRunning] = useState(false);
  const [isGameOver, setIsGameOver] = useState(false);
  const [isVictory, setIsVictory] = useState(false);
  const [score, setScore] = useState(0);
  const [mistakes, setMistakes] = useState(0);

  // Generate randomized valid puzzle
  const generatePuzzle = useCallback((diff: Difficulty) => {
    // 1. Shuffle digit mappings (1..9 permutation)
    const map = [1, 2, 3, 4, 5, 6, 7, 8, 9].sort(() => 0.5 - Math.random());
    const newSolution = BASE_SOLUTION.map(row => row.map(val => map[val - 1]));

    // 2. Decide clues count based on difficulty
    const cluesCount = diff === 'easy' ? 44 : diff === 'medium' ? 34 : 26;

    // 3. Remove digits symmetrically
    const puzzle = newSolution.map(row => [...row]);
    const cellsToClear = 81 - cluesCount;
    let cleared = 0;

    while (cleared < cellsToClear) {
      const r = Math.floor(Math.random() * 9);
      const c = Math.floor(Math.random() * 9);
      if (puzzle[r][c] !== 0) {
        puzzle[r][c] = 0;
        cleared++;
      }
    }

    setInitialBoard(puzzle.map(row => [...row]));
    setBoard(puzzle.map(row => [...row]));
    setSolution(newSolution);
    setNotes({});
    setSelectedCell([0, 0]);
    setHintsLeft(3);
    setTimer(0);
    setIsTimerRunning(true);
    setIsGameOver(false);
    setIsVictory(false);
    setScore(0);
    setMistakes(0);
  }, []);

  useEffect(() => {
    generatePuzzle(difficulty);
  }, [difficulty, generatePuzzle]);

  // Timer loop
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (isTimerRunning && !isGameOver && !isVictory) {
      interval = setInterval(() => setTimer(t => t + 1), 1000);
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerRunning, isGameOver, isVictory]);

  // Check conflicts
  const isConflict = (r: number, c: number, val: number): boolean => {
    if (val === 0) return false;

    // Check row
    for (let i = 0; i < 9; i++) {
      if (i !== c && board[r][i] === val) return true;
    }
    // Check column
    for (let i = 0; i < 9; i++) {
      if (i !== r && board[i][c] === val) return true;
    }
    // Check 3x3 block
    const br = Math.floor(r / 3) * 3;
    const bc = Math.floor(c / 3) * 3;
    for (let i = 0; i < 3; i++) {
      for (let j = 0; j < 3; j++) {
        const nr = br + i;
        const nc = bc + j;
        if ((nr !== r || nc !== c) && board[nr][nc] === val) return true;
      }
    }
    return false;
  };

  const handleInputDigit = useCallback((digit: number) => {
    if (!selectedCell || isGameOver || isVictory) return;
    const [r, c] = selectedCell;

    // Cannot edit initial clue cells
    if (initialBoard[r][c] !== 0) return;

    if (notesMode) {
      // Toggle note
      const key = `${r}-${c}`;
      const curNotes = notes[key] || [];
      const nextNotes = curNotes.includes(digit)
        ? curNotes.filter(n => n !== digit)
        : [...curNotes, digit].sort();
      setNotes(n => ({ ...n, [key]: nextNotes }));
      playMoveSound();
      return;
    }

    playMoveSound();
    triggerHaptic(15);

    const nextBoard = board.map(row => [...row]);
    nextBoard[r][c] = digit;
    setBoard(nextBoard);

    // Clear notes on this cell
    setNotes(n => {
      const copy = { ...n };
      delete copy[`${r}-${c}`];
      return copy;
    });

    // Check if error against solution
    if (digit !== solution[r][c]) {
      setMistakes(m => m + 1);
    }

    // Check if whole board complete and valid
    let complete = true;
    for (let i = 0; i < 9; i++) {
      for (let j = 0; j < 9; j++) {
        if (nextBoard[i][j] !== solution[i][j]) {
          complete = false;
          break;
        }
      }
      if (!complete) break;
    }

    if (complete) {
      playClearSound();
      triggerHaptic(40);
      setIsVictory(true);
      setIsGameOver(true);
      setIsTimerRunning(false);
      const diffBonus = difficulty === 'hard' ? 600 : difficulty === 'medium' ? 300 : 100;
      const finalScore = Math.max(200, 1500 + diffBonus - mistakes * 50 - timer * 2);
      setScore(finalScore);
    }
  }, [selectedCell, isGameOver, isVictory, initialBoard, notesMode, notes, board, solution, difficulty, mistakes, timer]);

  const handleErase = () => {
    if (!selectedCell || isGameOver || isVictory) return;
    const [r, c] = selectedCell;
    if (initialBoard[r][c] !== 0) return;

    playMoveSound();
    const nextBoard = board.map(row => [...row]);
    nextBoard[r][c] = 0;
    setBoard(nextBoard);

    setNotes(n => {
      const copy = { ...n };
      delete copy[`${r}-${c}`];
      return copy;
    });
  };

  const handleHint = () => {
    if (!selectedCell || hintsLeft <= 0 || isGameOver || isVictory) return;
    const [r, c] = selectedCell;
    if (initialBoard[r][c] !== 0 || board[r][c] === solution[r][c]) return;

    playClearSound();
    triggerHaptic(25);
    const nextBoard = board.map(row => [...row]);
    nextBoard[r][c] = solution[r][c];
    setBoard(nextBoard);
    setHintsLeft(h => h - 1);
  };

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (['1', '2', '3', '4', '5', '6', '7', '8', '9'].includes(e.key)) {
        handleInputDigit(parseInt(e.key, 10));
      } else if (e.key === 'Backspace' || e.key === 'Delete') {
        handleErase();
      } else if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) {
        if (!selectedCell) return;
        const [r, c] = selectedCell;
        if (e.key === 'ArrowUp') setSelectedCell([Math.max(0, r - 1), c]);
        if (e.key === 'ArrowDown') setSelectedCell([Math.min(8, r + 1), c]);
        if (e.key === 'ArrowLeft') setSelectedCell([r, Math.max(0, c - 1)]);
        if (e.key === 'ArrowRight') setSelectedCell([r, Math.min(8, c + 1)]);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [handleInputDigit, selectedCell]);

  const selectedValue = selectedCell ? board[selectedCell[0]]?.[selectedCell[1]] ?? 0 : 0;

  return (
    <GameShell
      game={gameMeta}
      score={score}
      isGameOver={isGameOver}
      isPaused={false}
      onRestart={() => generatePuzzle(difficulty)}
      onBackToHub={onBackToHub}
      isVictory={isVictory}
      gameCustomStats={
 <div className="flex items-center gap-2">
 <div className="bg-slate-950/80 px-2.5 py-1 rounded-xl border border-slate-800 text-xs flex items-center gap-1.5 text-slate-400">
 <Clock className="w-3.5 h-3.5 text-amber-400" />
 <span className="font-bold text-white">{timer}s</span>
          </div>
          {mistakes > 0 && (
 <div className="bg-slate-950/80 px-2 py-1 rounded-xl border border-slate-800 text-xs text-rose-400 font-bold">
              Lỗi: {mistakes}
            </div>
          )}
        </div>
      }
    >
 <div className="flex flex-col items-center justify-center w-full max-w-md mx-auto">
        {/* Difficulty switcher */}
        <div
 className="flex items-center gap-1.5 p-1 mb-3"
          style={{
            background: 'rgba(2,6,23,0.9)',
            border: '1px solid rgba(51,65,85,0.9)',
            borderRadius: '1rem',
          }}
        >
          {(['easy', 'medium', 'hard'] as Difficulty[]).map(d => (
            <button
              key={d}
              onClick={() => setDifficulty(d)}
 className="px-3 py-1.5 rounded-xl text-xs font-bold transition-all"
              style={
                difficulty === d
                  ? {
                      background: '#4338ca',
                      color: '#fff',
                    }
                  : {
                      color: '#94a3b8',
                    }
              }
            >
              {d === 'easy' ? 'Dễ' : d === 'medium' ? 'Vừa' : 'Khó'}
            </button>
          ))}
        </div>

        {/* 9x9 Sudoku Board */}
        <div
 className="p-2 sm:p-3 rounded-3xl w-full max-w-[390px] aspect-square game-touch-zone"
          style={{
            background: '#020617',
            border: '2px solid rgba(71,85,105,0.9)',
          }}
        >
 <div className="grid grid-cols-9 gap-0.5 w-full h-full bg-slate-700 p-0.5 rounded-2xl">
            {board.map((row, r) =>
              row.map((val, c) => {
                const isSelected = selectedCell?.[0] === r && selectedCell?.[1] === c;
                const isInitial = initialBoard[r]?.[c] !== 0;
                const isSameRowOrCol =
                  selectedCell && (selectedCell[0] === r || selectedCell[1] === c);
                const isSameValue = selectedValue > 0 && val === selectedValue;
                const conflict = isConflict(r, c, val);
                const cellNotes = notes[`${r}-${c}`] || [];

                // 3x3 box borders
                const borderRight = (c + 1) % 3 === 0 && c < 8 ? 'border-r-2 border-r-slate-500' : '';
                const borderBottom = (r + 1) % 3 === 0 && r < 8 ? 'border-b-2 border-b-slate-500' : '';

                return (
                  <button
                    key={`${r}-${c}`}
                    onClick={() => {
                      setSelectedCell([r, c]);
                      playMoveSound();
                    }}
 className={`relative flex items-center justify-center font-bold text-sm sm:text-base transition-colors select-none ${borderRight} ${borderBottom} ${
                      isSelected ? 'text-white z-10 scale-105 rounded-md' : conflict ? 'text-rose-400' : isSameValue ? 'text-indigo-300' : isSameRowOrCol ? 'text-white' : 'text-slate-100'
                    }`}
                    style={
                      isSelected
                        ? {
                            background: '#4338ca',
                          }
                        : conflict
                          ? {
                              background: 'rgba(159,18,57,0.25)',
                            }
                          : isSameValue
                            ? {
                                background: 'rgba(67,56,202,0.25)',
                              }
                            : isSameRowOrCol
                              ? { background: 'rgba(30,41,59,0.85)' }
                              : {
                                  background: 'rgba(2,6,23,0.95)',
                                }
                    }
                  >
                    {val > 0 ? (
 <span className={isInitial ? 'font-black text-indigo-300' : ''}>
                        {val}
                      </span>
                    ) : cellNotes.length > 0 ? (
 <div className="grid grid-cols-3 gap-0.5 text-[8px] text-slate-400 p-0.5 pointer-events-none">
                        {[1, 2, 3, 4, 5, 6, 7, 8, 9].map(n => (
 <span key={n} className="leading-none text-center">
                            {cellNotes.includes(n) ? n : ''}
                          </span>
                        ))}
                      </div>
                    ) : null}
                  </button>
                );
              })
            )}
          </div>
        </div>

        {/* Actions bar: Notes, Erase, Hint */}
 <div className="flex items-center justify-center gap-3 w-full max-w-sm mt-3">
          <button
            onClick={() => {
              setNotesMode(!notesMode);
              playMoveSound();
            }}
 className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold border transition ${
              notesMode
                ? 'bg-indigo-600 text-white border-indigo-500 '
                : 'bg-slate-800 text-slate-300 border-slate-700 hover:text-white'
            }`}
          >
 <Edit3 className="w-3.5 h-3.5" />
            <span>Ghi chú {notesMode ? 'BẬT' : 'TẮT'}</span>
          </button>

          <button
            onClick={handleErase}
 className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-xs font-bold border border-slate-700 transition"
          >
 <Eraser className="w-3.5 h-3.5" />
            <span>Xóa số</span>
          </button>

          <button
            onClick={handleHint}
            disabled={hintsLeft <= 0}
 className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 text-xs font-bold border border-amber-500/30 disabled:opacity-40 transition"
          >
 <Lightbulb className="w-3.5 h-3.5" />
            <span>Gợi ý ({hintsLeft})</span>
          </button>
        </div>

        {/* Numpad 1 to 9 */}
 <div className="grid grid-cols-9 gap-1.5 w-full max-w-sm mt-3">
          {[1, 2, 3, 4, 5, 6, 7, 8, 9].map(n => (
            <button
              key={`num-${n}`}
              onClick={() => handleInputDigit(n)}
 className="py-3 rounded-xl text-white font-black text-sm border border-slate-600 transition-all game-btn-press"
              style={{
                background: '#1e293b',
                borderColor: 'rgba(100,116,139,0.7)',
              }}
            >
              {n}
            </button>
          ))}
        </div>
      </div>
    </GameShell>
  );
};
